project:
  type: book

book:
  title: "03 Prova tesi"
  author: "Andrea Nazzaro"
  date: "27/11/2025"
  page-footer: "eurusne"
  chapters:
    - index.qmd
    - chapter1.qmd
    - chapter2.qmd
    - references.qmd

format:
  pdf:
    documentclass: book
    papersize: a4
    fontsize: 12pt
    margin-left: 1in   # Adjust margins for binding
    margin-right: 1in
    include-in-header: 
      text: |
        \usepackage{setspace}
    include-before-body: Frontespizio.tex
    toc: true            # Table of Contents
    number-sections: true
    colorlinks: true    
    fontfamily: times

editor: visual

